---
  dataSource: "milestones"
  onlyMilestones: true
  milestoneMatch: "{{tag_name}}"
  template:
    group: "\n### {{heading}}\n"
  changelogFilename: "CHANGELOG.md"
  ignore-tags-with:
    - "Relearn"
  ignoreLabels:
    - "documentation"
    - "duplicate"
    - "invalid"
    - "support"
    - "wontfix"
  groupBy:
    Bug Fixes:
      - "bug"
    New features:
      - "feature"
    Maintenance:
      - "task"
    Uncategorised:
      - "closed"
