# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Relearn"
license = "MIT"
licenselink = "https://github.com/McShelby/hugo-theme-relearn/blob/master/LICENSE.md"
description = "Documentation theme for Hugo"
homepage = "https://github.com/McShelby/hugo-theme-relearn/"
repo = "https://github.com/McShelby/hugo-theme-relearn"
tags = ["documentation", "grav", "learn", "relearn", "doc", "search"]
features = ["documentation", "menu", "nested sections", "search", "mermaid"]
min_version = 0.25

[author]
  name = "Sören Weber & others"
  homepage = "https://github.com/McShelby"
